AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    getTweet lambda
Resources:
    GetTweetFastAPILambdaV3:
        Type: AWS::Serverless::Function
        Properties:
            Events:
                ApiEvent:
                    Properties:
                        RestApiId:
                            Ref: GetTweetApiGatewayV3
                        Path: /{proxy+}
                        Method: ANY
                    Type: Api
            FunctionName: getweet-lambda-v3
            CodeUri: ./
            Handler: api_server.handler
            Runtime: python3.8
            Timeout: 300 # timeout of your lambda function
            MemorySize: 256 # memory size of your lambda function
            Description: getTweet lambda
            # other options, see ->
            # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html#sam-specification-template-anatomy-globals-supported-resources-and-properties
            Role: arn:aws:iam::675191224949:role/service-role/getTweet-test-role-jemoq2hk

    GetTweetApiGatewayV3:
        Type: AWS::Serverless::Api
        Properties:
            StageName: prod
            OpenApiVersion: '3.0.0'
