name: frontend_deploy
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        ALL_FILES=`git diff-tree --no-commit-id --name-only -r ${{ github.sha }}`
        echo "All files : $ALL_FILES"
