name: frontend_deploy
on:
  push:
    branches: master
jobs:
  frontend_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deployment Steps
      run: |
        ALL_FILES=`git diff-tree --no-commit-id --name-only -r ${{ github.sha }}`
        echo "All files : $ALL_FILES"
