name: frontend_deploy
on:
  push:
    branches: master
jobs:
  frontend_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 2
    - name: Deployment Steps
      run: |
        npm --version
        IS_FRONTEND=`git diff-tree --name-only -r HEAD^ HEAD|tr " " "\n" |grep -Ec "^src\/|^public\/" || true`
        echo "IS_FRONTEND ---> $IS_FRONTEND"
        if [ $IS_FRONTEND -eq 0 ];then
          echo "No frontend files found exiting !"
          exit 0
        fi
        echo "✅ Frontend Files found, starting deployment ...."
        npm run build
        aws s3 sync ./build s3://$FRONTEND_BUCKET_NAME
        aws cloudfront create-invalidation --distribution-id $CDN_DISTRIBUTION_ID --paths "/*"
      env:	
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}	
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}	
        AWS_REGION: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        CDN_DISTRIBUTION_ID: ${{ secrets.CDN_DISTRIBUTION_ID }}
        FRONTEND_BUCKET_NAME: ${{ secrets.FRONTEND_BUCKET_NAME }}
        
